### PR TITLE
remove custom futureTask, use standard CompletableFuture instead.

### PR DESCRIPTION
**Pull request by twoyao**
MasterFutureTask and SlaveFutureTask is not clear and error-prone.
When I fork this plugin and do some customize, I encounter a dead lock issue
because of the LOCK object in BranchInfo. These locks are useless since fetch & diff operation is fast.
So I replace with CompletableFuture which supports the same async effect and is clearer.

### CODE REVIEW

**Comment by PavlikPolivka** [comment]
Hi. Great work. Do you really need that lombok dependency just for one annotation? I am trying to keep the dependencies to minimum.

**Comment by twoyao** [comment]
I use lombok `@SneakyThrows(VcsException.class)` solve lambda checked exception issue. You can find the doc [here](https://projectlombok.org/features/SneakyThrows).

Basically, lombok will generate some boilerplate code for you **at compile time**, and it will not introduce any runtime dependency. So it will be fine.

**Comment by PavlikPolivka** [comment]
I had no idea that it has no runtime dependencies (it makes sense tho) in that case I would be fine with it.

**Comment by twoyao** [comment]
Later will be fine. I tested both.

**Pull request merged**
